# Generated by Django 6.0.5 on 2026-06-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='cadastro.curso'),
        ),
    ]
