# Generated by Django 6.0.5 on 2026-06-11 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_campus_turma_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_campus', to='cadastro.campus'),
        ),
    ]
